### ISSUE TITLE
Use https://github.com/commandlineparser/commandline for command line parsing

### ISSUE THREAD

**Issue by mmattner** [mmattner/vPinBackupManager#14]
https://github.com/commandlineparser/commandline (available as a Nuget https://www.nuget.org/packages/CommandLineParser/) is a package which will probably make command line processing easier and provide the abiltiy to greatly grow it down the track. 
Currenty we have tow options: --config and --run, where for the --run we provide a string with the command to run. This may get messy down the track if we allow 'lots' of paramters. 

Perhaps we should look to switch this, and do everythig with --/- style, ie:
vPinBackupManager --config blah.txt --run "backup 4 5 6 7" could get messy over time if we needed to add other flags lie --preview

maybe it could be written as something more like:
vPinBackupManager --config blah.txt  --command backup --preview 4 5 6 7

**Comment by linojon** [comment]
Makes sense, expecially if the interface will expand. i used something similar for pinman - Open CLI Framework (for typescript/node) https://oclif.io/ 

Also i had started a gitbook for documentation https://parkerhill.gitbook.io/pinman/reference/cli-reference

**Comment by mmattner** [comment]
Funnily enough it was your gitbook that reminded me that this is where we should be heading.

I might discuss the CLI paramters later with you but I think we get more flexibility with that approach, especially if we want to start injecting flags and settings into the system.


 (big game of football to watch tonight - my teams playingFriday Night Footy) .
