### ISSUE TITLE
Make safe mode the default

### ISSUE THREAD

**Issue by linojon** [mmattner/vPinBackupManager#23]
Safe mode should be the default so shared files are protected from deleting a table.

## GUI

make safe mode the default. 
Possibly add a checkbox to disable it (but why would you?). Or something more interactive like prompt user a warning when deleting a shared file?

## CLI

add `--no-safe` option (typical of binary options to have both `--safe` and `--no-safe`)

**Comment by mmattner** [comment]
For GUI, SAFE mode already is the default in fact its impossible not to use it.
In reality safe mode in itslef isnt a thing, its really just a flow on effect of the manifests that get created at startup, becuase GUI displays all games with color coding and content the manifests always have to be created.

I searched here: https://nullprogram.com/blog/2020/08/01/ for command line conventions and confirmed the proposed --safe and --no-safe options conform, so will implement, with --safe the default, and effectively doing nothing. I will remove the -s option as it doesnt made sense to have a -n

**Comment by mmattner** [comment]
On further consideration, I am goign with a slightly different approach for the CLI argument and removeing --safe entirely, this will be the defualt mode. 

Instead I am adding a --disable-delete-checks argument which is false by default. This name is more meaningful, and there is NO single character pattern for it. IF enabled then the checks we do by defualt for deletes will NOT occur.
