### ISSUE TITLE
Safe mode does not seem to be working on rom files

### ISSUE THREAD

**Issue by linojon** [mmattner/vPinBackupManager#25]
see https://github.com/mmattner/vPinBackupManager/pull/22

**Comment by mmattner** [comment]
To start diagnosing this I have setup (in GUI mdoe) a case where tow verisons of AFM are backed up). see images and note that both share same ROM and NVRAM (as an example):
![image](https://user-images.githubusercontent.com/483200/235804720-844d6558-7bd9-4d28-abb6-4da1bcda3d4c.png)
![image](https://user-images.githubusercontent.com/483200/235804754-1b83bd6e-2885-4315-ac5c-1524c70db9f7.png)

**Comment by mmattner** [comment]
A further note to consider. While testing I've been deleting/restoring games back and forth to check the delete works as expected. Often I was looping through the delete and watching each file get checked to see if it sohuld be or not. As is the case, the game files are usually the first files deleted as they are the first filter.
If I cancelled processing part way through - and before roms etc are deleted I am finding that on restart the app is not detecting these files for the game. This is expected as codes are parsed out of the gme script, although ROM is often found in the Pinup DB - lots of games havent had this set.

The case I found is if a gamefile is dleeted then a diff to backup weill throw on multiple files, even after the restore, as gameCodes are parsed up front and cached. After a restore the gameCode for a game should be recalculated and the cache value replaced regardless. (possibly you can limit this to just if the game script is restored - if its easy to handle in the code).


to test:
1. find a game that uses a rom, and ensure the rom isnt stored in pinupDB, but is parsed out of game script.
2. Backup the game.
3. Manually delete the game script and restart VPBM
4. Confirm that multiple files are shown as missing - ie the game file - andany file that depends on the gamecodes parsed out of it.
5. restore the game & confim all files are restored and diffs are showing green in gamelist
6. restart VPBM & confim all  diffs are showing green in gamelist

**Comment by mmattner** [comment]
Further to the above I have a solution that works. I also had to ad da small change to enmsure filename was passed to getGameCodes in UpdateRowStatus ... i was passing gamename meaning the emulator wasnt getting the correct rom codes in some circumsntces. Now thats done the following animated gif demonstrates safe mode working... note the rom files in the central file explorer window on the left and note fiels are only deleted AFTER the second AFM game is deleted. As an aside it looks like <gamename>.cfg ia another filter we need.

![SafeDelete](https://user-images.githubusercontent.com/483200/235907355-5bae7f30-929c-4fab-af53-a70e16524de4.gif)

I will clean up the changes and commit in  morning.
